config/routes.rb
Rails.application.routes.draw do
  root   'microposts#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/about',      to: 'static_pages#about'
  resources :microposts   #, only: [:index, :show, :create, :edit, :update, :destroy]
  # Will I implement 'edit' action in microposts?
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :reset_token
  before_save   :downcase_email
  has_many      :microposts, dependent: :destroy
  validates     :name, length: { maximum: 50 },
                              presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates     :email, length: { maximum: 244 }, presence: true,
                              format: { with: VALID_EMAIL_REGEX },
                              uniqueness: { case_sensitive: false }
  has_secure_password
  validates     :password, length: { minimum: 6 }, allow_nil: true, presence: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returts true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.all #paginate(page: params[:page])
  end

  def show
    
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "User was successfully updated."
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User was successfully deleted"
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white 
    # list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)

    end

    # Before filters

    # Confirm the correct user.
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @microposts = @user.microposts
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_are_users.html.erb
<h1>Users</h1>

<%#= will_paginate %>

<div class="users">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <body>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
        <td>
           | <%= link_to "delete", user, method: :delete,
                                         data: { confirm: "You sure?" } %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </body>
</table>
</div>
<%#= will_paginate %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited
        this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_no_users.html.erb
<h1>No users.</h1>
<h2><%= link_to 'Sign up', new_user_path %></h2>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="">
  <% if @users.any? %>
    <%= render 'are_users' %>
  <% else %>
    <%= render 'no_users' %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %></h1>

<h4><%= mail_to @user.email, @user.email %></h4>

<h3><%= @user.microposts.count %> microposts</h3>

<% if @microposts.any? %>
  <ol class="microposts">
    <%= render @microposts %>
  </ol>
<% end %>