config/routes.rb
Rails.application.routes.draw do
  root   'microposts#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/about',      to: 'static_pages#about'
  resources :microposts   #, only: [:index, :show, :create, :edit, :update, :destroy]
  # Will I implement 'edit' action in microposts?
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, length: { maximum: 240 }, presence: true
  validates :user_id, presence: true
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost,  only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :create, :destroy]
  before_action :correct_user,   only: :destroy

  def index
    @microposts = Micropost.all
    @micropost = current_user.microposts.build if logged_in?
  end

  def show
    @user = User.find(@micropost.user_id)
  end

  def edit
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Post was successfully created."
      redirect_to request.referrer || root_url
    else
      flash[:danger] = "Post can't be blank and should have no more than 240 characters."
      redirect_to request.referrer || root_url
    end
  end

  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        flash[:success] = "Micropost was successfully updated."
        format.html { redirect_to @micropost }
        format.json { render :show, status: :ok,
          location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors,
          status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost was successfully destroyed."
    redirect_to request.referrer || root_url
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      unless current_user.admin?
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %>
        prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, placeholder: "Post something..."  %>
  </div>

  <div class="actions">
    <%= f.submit "Create post" %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  <%= link_to 'Show', micropost %>
  <% if current_user?(micropost.user) || !current_user.nil? && current_user.admin? %>
  <%= link_to ' | Delete', micropost, method: :delete, data: 
  { confirm: 'Are you sure?' } %>
  <% end %>
  </span>
</li>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Feed</h1>

<% if logged_in? %>
  <%= render 'form', micropost: @micropost %>
<% end %>

<% if @microposts.any? %>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
<% else %>
  <h1>No posts.</h1>
<% end %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <b><%= link_to @micropost.user.name, @user %></b>
| Created at: <%= @micropost.created_at %></p>

<h3><%= @micropost.content %></h3>

<%= link_to 'Edit', edit_micropost_path(@micropost) %>
<%= render html: " | " %>
<%= link_to 'Back', root_path %>