config/routes.rb
Rails.application.routes.draw do
  root   'microposts#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/about',      to: 'static_pages#about'
  resources :microposts   #, only: [:index, :show, :create, :edit, :update, :destroy]
  # Will I implement 'edit' action in microposts?
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container" >
    <%= link_to "Toy Post", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Users",  users_path %></li>
        <li><%= link_to "About",  about_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile",  current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all',
 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toy Post</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    </head>
    <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </body>
  </html>